function Hd = filter_design
%FILTER DESIGN Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 13-May-2022 16:55:25

% Equiripple Bandstop filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 150;  % Sampling Frequency

N      = 150;  % Order
Fpass1 = 46;   % First Passband Frequency
Fstop1 = 48;   % First Stopband Frequency
Fstop2 = 52;   % Second Stopband Frequency
Fpass2 = 54;   % Second Passband Frequency
Wpass1 = 1;    % First Passband Weight
Wstop  = 1;    % Stopband Weight
Wpass2 = 1;    % Second Passband Weight
dens   = 20;   % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fpass1 Fstop1 Fstop2 Fpass2 Fs/2]/(Fs/2), [1 1 0 0 1 ...
           1], [Wpass1 Wstop Wpass2], {dens});
Hd = dfilt.dffir(b);

% [EOF]
